[project]
name = "titanic"
version = "0.1.0"
description = "Titanic Data - Basic EDA - Classification (Python)"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.1",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
]
